
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Use a reference to the Database type without direct import
// to avoid duplicate identifier errors
const SUPABASE_URL = "https://hewyffhdykietximpfbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhld3lmZmhkeWtpZXR4aW1wZmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMjk1ODYsImV4cCI6MjA1ODkwNTU4Nn0.UqxDgfYqm3yhC8nDYdfcb8UDm9rz9qFKq-pIh6xEB-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the client with a generic type that refers to the Database type
// from the generated types file without importing it directly
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
